# Generated by Django 3.2.25 on 2025-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_date_of_birth_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='emergency_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
