# Generated by Django 3.2.25 on 2025-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250413_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='emergency_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
