# Generated by Django 3.2.25 on 2025-04-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='receptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_reviewed', to='core.receptionist'),
        ),
    ]
