# Generated by Django 3.2.25 on 2025-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_booking_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
